import { formatCurrencyAmount } from '../../shared/utils/formatters';
import type {
  ExpenseMovementItem,
  ExchangeMovementItem,
  IncomeMovementItem,
  MovementListItem,
  TransferMovementItem,
} from './movements.models';

type IncomeSeed = Omit<
  IncomeMovementItem,
  'kind' | 'dateLabel' | 'amountLabel' | 'kindLabel' | 'kindTone' | 'kindIcon'
>;
type ExpenseSeed = Omit<
  ExpenseMovementItem,
  'kind' | 'dateLabel' | 'amountLabel' | 'kindLabel' | 'kindTone' | 'kindIcon'
>;
type TransferSeed = Omit<
  TransferMovementItem,
  'kind' | 'dateLabel' | 'amountLabel' | 'kindLabel' | 'kindTone' | 'kindIcon'
>;
type ExchangeSeed = Omit<
  ExchangeMovementItem,
  'kind' | 'dateLabel' | 'amountLabel' | 'kindLabel' | 'kindTone' | 'kindIcon'
>;

const formatDate = (date: string) =>
  new Intl.DateTimeFormat('es-AR', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  }).format(new Date(`${date}T12:00:00`));

const makeIncome = (item: IncomeSeed): IncomeMovementItem => ({
  ...item,
  kind: 'income',
  kindLabel: 'Ingreso',
  kindTone: 'favorable',
  kindIcon: 'income',
  dateLabel: formatDate(item.date),
  amountLabel: formatCurrencyAmount(item.amount, item.currency),
});

const makeExpense = (item: ExpenseSeed): ExpenseMovementItem => ({
  ...item,
  kind: 'expense',
  kindLabel: 'Gasto',
  kindTone: 'warning',
  kindIcon: 'expense',
  dateLabel: formatDate(item.date),
  amountLabel: formatCurrencyAmount(item.amount, item.currency),
});

const makeTransfer = (item: TransferSeed): TransferMovementItem => ({
  ...item,
  kind: 'transfer',
  kindLabel: 'Transferencia',
  kindTone: 'neutral',
  kindIcon: 'transfer',
  dateLabel: formatDate(item.date),
  amountLabel: formatCurrencyAmount(item.amount, item.currency),
});

const makeExchange = (item: ExchangeSeed): ExchangeMovementItem => ({
  ...item,
  kind: 'exchange',
  kindLabel: 'Cambio',
  kindTone: 'info',
  kindIcon: 'exchange',
  dateLabel: formatDate(item.date),
  amountLabel: item.fromAmountLabel,
});

export const MOVEMENTS_MOCK_ITEMS: readonly MovementListItem[] = [
  makeIncome({
    id: 'mov-2026-08-01-income-1',
    date: '2026-08-01',
    description: 'Sueldo mensual',
    notes: 'Acreditación programada del mes.',
    amount: 1860000,
    currency: 'ARS',
    accountLabel: 'Banco Principal',
    categoryLabel: 'Ingresos',
    subcategoryLabel: 'Sueldo',
    sourceLabel: 'Empresa Demo',
  }),
  makeExpense({
    id: 'mov-2026-08-02-expense-1',
    date: '2026-08-02',
    description: 'Alquiler mensual',
    notes: 'Pago mensual del contrato vigente.',
    amount: 680000,
    currency: 'ARS',
    accountLabel: 'Cuenta Haberes',
    categoryLabel: 'Vivienda',
    subcategoryLabel: 'Alquiler',
    sourceLabel: 'Inmobiliaria Demo',
  }),
  makeExpense({
    id: 'mov-2026-08-03-expense-2',
    date: '2026-08-03',
    description: 'Compra de supermercado',
    notes: 'Reposición semanal de alimentos y artículos básicos.',
    amount: 54300,
    currency: 'ARS',
    accountLabel: 'Billetera ARS',
    categoryLabel: 'Alimentación',
    subcategoryLabel: 'Supermercado',
    sourceLabel: 'Comercio Demo',
  }),
  makeTransfer({
    id: 'mov-2026-08-04-transfer-1',
    date: '2026-08-04',
    description: 'Transferencia a cuenta de inversión',
    notes: 'Movimiento interno sin impacto en patrimonio total.',
    amount: 420000,
    currency: 'ARS',
    categoryLabel: null,
    subcategoryLabel: null,
    fromAccountLabel: 'Banco Principal',
    toAccountLabel: 'Billetera ARS',
    counterpartyLabel: null,
  }),
  makeIncome({
    id: 'mov-2026-08-05-income-2',
    date: '2026-08-05',
    description: 'Ingreso por consultoría',
    notes: 'Factura emitida a cliente genérico.',
    amount: 420000,
    currency: 'ARS',
    accountLabel: 'Cuenta Haberes',
    categoryLabel: 'Ingresos',
    subcategoryLabel: 'Consultoría',
    sourceLabel: 'Cliente Demo',
  }),
  makeExpense({
    id: 'mov-2026-08-06-expense-3',
    date: '2026-08-06',
    description: 'Combustible',
    notes: 'Carga de combustible y peaje.',
    amount: 31200,
    currency: 'ARS',
    accountLabel: 'Billetera ARS',
    categoryLabel: 'Transporte',
    subcategoryLabel: 'Combustible',
    sourceLabel: 'Movilidad Demo',
  }),
  makeExchange({
    id: 'mov-2026-08-07-exchange-1',
    date: '2026-08-07',
    description: 'Compra de USD para cobertura',
    notes: 'Cambio de moneda sin impacto operativo en ingresos o gastos.',
    amount: 120000,
    fromCurrency: 'ARS',
    fromAmount: 120000,
    fromAmountLabel: formatCurrencyAmount(120000, 'ARS'),
    toCurrency: 'USD',
    toAmount: 92,
    toAmountLabel: formatCurrencyAmount(92, 'USD'),
    categoryLabel: null,
    subcategoryLabel: null,
    fromAccountLabel: 'Banco Principal',
    toAccountLabel: 'Cuenta USD',
    commissionLabel: formatCurrencyAmount(1500, 'ARS'),
  }),
  makeExpense({
    id: 'mov-2026-08-08-expense-4',
    date: '2026-08-08',
    description: 'Suscripción de software',
    notes: 'Servicio recurrente mensual.',
    amount: 15400,
    currency: 'USD',
    accountLabel: 'Cuenta USD',
    categoryLabel: 'Servicios',
    subcategoryLabel: 'Suscripciones',
    sourceLabel: 'Proveedor Demo',
  }),
  makeIncome({
    id: 'mov-2026-08-09-income-3',
    date: '2026-08-09',
    description: 'Intereses acreditados',
    notes: 'Rendimiento de cuenta remunerada.',
    amount: 34,
    currency: 'USD',
    accountLabel: 'Cuenta USD',
    categoryLabel: 'Rendimientos',
    subcategoryLabel: 'Cuenta remunerada',
    sourceLabel: 'Cuenta remunerada',
  }),
  makeTransfer({
    id: 'mov-2026-08-10-transfer-2',
    date: '2026-08-10',
    description: 'Transferencia entre cuentas propias',
    notes: 'Banco hacia billetera, mismo ecosistema financiero.',
    amount: 135000,
    currency: 'ARS',
    categoryLabel: null,
    subcategoryLabel: null,
    fromAccountLabel: 'Banco Principal',
    toAccountLabel: 'Billetera ARS',
    counterpartyLabel: null,
  }),
  makeExpense({
    id: 'mov-2026-08-11-expense-5',
    date: '2026-08-11',
    description: 'Atención médica',
    notes: 'Consulta y estudio de rutina.',
    amount: 82000,
    currency: 'ARS',
    accountLabel: null,
    categoryLabel: 'Salud',
    subcategoryLabel: 'Consulta',
    sourceLabel: 'Centro médico Demo',
  }),
  makeExpense({
    id: 'mov-2026-08-12-expense-6',
    date: '2026-08-12',
    description: 'Cena con amigos',
    notes: 'Salida de la semana.',
    amount: 18900,
    currency: 'ARS',
    accountLabel: 'Tarjeta Débito',
    categoryLabel: 'Alimentación',
    subcategoryLabel: 'Restaurantes',
    sourceLabel: 'Comercio Demo',
  }),
  makeIncome({
    id: 'mov-2026-08-13-income-4',
    date: '2026-08-13',
    description: 'Reintegro de compra',
    notes: 'Devolución por nota de crédito.',
    amount: 14600,
    currency: 'ARS',
    accountLabel: null,
    categoryLabel: 'Reintegros',
    subcategoryLabel: 'Compra',
    sourceLabel: 'Comercio Demo',
  }),
  makeExpense({
    id: 'mov-2026-08-14-expense-7',
    date: '2026-08-14',
    description: 'Pasaje aéreo',
    notes: 'Compra para viaje laboral.',
    amount: 620,
    currency: 'USD',
    accountLabel: 'Cuenta USD',
    categoryLabel: 'Viajes',
    subcategoryLabel: 'Pasajes',
    sourceLabel: 'Aerolínea Demo',
  }),
  makeTransfer({
    id: 'mov-2026-08-15-transfer-3',
    date: '2026-08-15',
    description: 'Aporte a cuenta remunerada',
    notes: 'Sin impacto en el neto del período.',
    amount: 250000,
    currency: 'ARS',
    categoryLabel: null,
    subcategoryLabel: null,
    fromAccountLabel: 'Billetera ARS',
    toAccountLabel: 'Cuenta remunerada',
    counterpartyLabel: null,
  }),
  makeExchange({
    id: 'mov-2026-08-16-exchange-2',
    date: '2026-08-16',
    description: 'Venta parcial de USD',
    notes: 'Conversión para cubrir pagos locales.',
    amount: 92,
    fromCurrency: 'USD',
    fromAmount: 92,
    fromAmountLabel: formatCurrencyAmount(92, 'USD'),
    toCurrency: 'ARS',
    toAmount: 121500,
    toAmountLabel: formatCurrencyAmount(121500, 'ARS'),
    categoryLabel: null,
    subcategoryLabel: null,
    fromAccountLabel: 'Cuenta USD',
    toAccountLabel: 'Banco Principal',
    commissionLabel: formatCurrencyAmount(8, 'USD'),
  }),
  makeExpense({
    id: 'mov-2026-08-17-expense-8',
    date: '2026-08-17',
    description: 'Mantenimiento del hogar',
    notes: 'Reparación menor y repuestos.',
    amount: 97500,
    currency: 'ARS',
    accountLabel: 'Banco Principal',
    categoryLabel: 'Vivienda',
    subcategoryLabel: 'Mantenimiento',
    sourceLabel: 'Proveedor Demo',
  }),
  makeIncome({
    id: 'mov-2026-08-18-income-5',
    date: '2026-08-18',
    description: 'Dividendos internacionales',
    notes: 'Ingreso percibido en moneda extranjera.',
    amount: 126,
    currency: 'USD',
    accountLabel: 'Cuenta USD',
    categoryLabel: 'Inversiones',
    subcategoryLabel: 'Dividendos',
    sourceLabel: 'Broker Demo',
  }),
  makeExpense({
    id: 'mov-2026-08-19-expense-9',
    date: '2026-08-19',
    description: 'Compra de supermercado con lista extensa para probar el recorte de texto',
    notes: 'Ejemplo para probar descripciones largas sin romper la grilla.',
    amount: 1248000,
    currency: 'ARS',
    accountLabel: 'Tarjeta Débito',
    categoryLabel: 'Alimentación',
    subcategoryLabel: 'Supermercado',
    sourceLabel: 'Comercio Demo',
  }),
  makeTransfer({
    id: 'mov-2026-08-20-transfer-4',
    date: '2026-08-20',
    description: 'Traslado entre cuentas sin categoría histórica',
    notes: 'Registro histórico sin cuenta de origen asociada.',
    amount: 86000,
    currency: 'ARS',
    categoryLabel: null,
    subcategoryLabel: null,
    fromAccountLabel: null,
    toAccountLabel: 'Billetera ARS',
    counterpartyLabel: null,
  }),
];
